name: Compile
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git mingw-w64-x86_64-toolchain
      - name: CI-Build
        run: |
          echo 'Running in MSYS2!'
          pacman -S --noconfirm mingw-w64-i686-binutils mingw-w64-i686-gcc mingw-w64-i686-gdb
          pacman -S --noconfirm make pkgconfig autoconf automake libtool intltool
          pacman -S --noconfirm mingw-w64-i686-gtk3
          pacman -S --noconfirm mingw-w64-i686-curl
          echo CI run autogen.sh ....
          . autogen.sh
          echo CI run configure....
          ./configure --disable-notify --disable-gstreamer  _WINDOWS=1 NDEBUG=1
          echo CI make....
          make
